#include "MainWindow.h"
#include "ui_mainwindow.h" // This is auto-generated by CMake from your mainwindow.ui
#include <QPushButton>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    this->setFixedSize(380, 550);

    // Wire Digit Buttons (Assuming they are named btn0, btn1, etc. in Qt Designer)
    connect(ui->btn0, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn1, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn2, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn3, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn4, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn5, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn6, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn7, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn8, &QPushButton::clicked, this, &MainWindow::digitPressed);
    connect(ui->btn9, &QPushButton::clicked, this, &MainWindow::digitPressed);

    // Wire Operator Buttons
    connect(ui->btnAdd, &QPushButton::clicked, this, &MainWindow::operatorPressed);
    connect(ui->btnSubtract, &QPushButton::clicked, this, &MainWindow::operatorPressed);
    connect(ui->btnMultiply, &QPushButton::clicked, this, &MainWindow::operatorPressed);
    connect(ui->btnDivide, &QPushButton::clicked, this, &MainWindow::operatorPressed);

    // Wire Equal Button
    connect(ui->btnEqual, &QPushButton::clicked, this, &MainWindow::equalPressed);

    // Wire Clear Button
    connect(ui->btnClear, &QPushButton::clicked, this, &MainWindow::clearPressed);

    // Optional: Wire a Clear Button if you add one to your UI
    // connect(ui->btnClear, &QPushButton::clicked, [&](){
    //     engine.clear();
    //     ui->display->setText(engine.getDisplayText());
    // });
}

MainWindow::~MainWindow() {
    delete ui; // Crucial: Prevents memory leaks by destroying the UI when the window closes
}

void MainWindow::digitPressed() {
    // Identify exactly which button triggered this slot
    QPushButton *button = qobject_cast<QPushButton*>(sender());
    if (button) {
        int digit = button->text().toInt(); // Extract the number from the button text

        engine.appendDigit(digit); // Pass it to the backend
        ui->display->setText(engine.getDisplayText()); // Update the screen
    }
}

void MainWindow::operatorPressed() {
    QPushButton *button = qobject_cast<QPushButton*>(sender());
    if (button) {
        QString opText = button->text();

        // Map the button's text symbol to our backend Enum
        if (opText == "+") {
            engine.setOperator(MathEngine::Add);
        } else if (opText == "-") {
            engine.setOperator(MathEngine::Subtract);
        } else if (opText == "*" || opText == "×") {
            engine.setOperator(MathEngine::Multiply);
        } else if (opText == "/" || opText == "÷") {
            engine.setOperator(MathEngine::Divide);
        }
    }
}

void MainWindow::equalPressed() {
    engine.calculateResult();
    ui->display->setText(engine.getDisplayText()); // Pull the final answer from the engine
}

void MainWindow::clearPressed() {
    engine.clear(); // Resets the math logic and sets internal display to "0"
    ui->display->setText(engine.getDisplayText()); // Updates the QLineEdit
}
